### ISSUE TITLE
wrong sample code?

### ISSUE THREAD

**Issue by CesarAV** [aspnet/EntityFramework.Docs.es-es#10]
In the first code sample, line 9:

    // Set the Name property to a new value
    context.Entry(name).Property(u =&gt; u.Name).CurrentValue = "My Fancy Blog";

Should it be
 
    context.Entry(blog).Property …

instead?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ vinculación de problemas de GitHub.*

* ID: fe4e1787-3d61-e5f3-ba22-f9de0adb6c9f
* Version Independent ID: 86f26f36-9727-244d-93c8-709f4ef72a08
* Content: [Trabajar con valores de propiedad - EF6](https://docs.microsoft.com/es-mx/ef/ef6/saving/change-tracking/property-values#feedback)
* Content Source: [entity-framework/ef6/saving/change-tracking/property-values.md](https://github.com/aspnet/EntityFramework.Docs.es-es/blob/live/entity-framework/ef6/saving/change-tracking/property-values.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by CeciAc** [comment]
Hello, @CesarAV 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/EntityFramework.Docs/issues/1545

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by divega** [comment]
@CesarAV tenías razón. Corregido en https://github.com/aspnet/EntityFramework.Docs/pull/1546. ¡Gracias!
